Loading conda_R/3.6.x

Attaching package: ‘lubridate’

The following object is masked from ‘package:base’:

    date


Attaching package: ‘dplyr’

The following objects are masked from ‘package:lubridate’:

    intersect, setdiff, union

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error in gzfile(file, "rb") : cannot open the connection
Calls: read_rds -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/dcl01/chatterj/data/ukbiobank/phenotype/accelerometer/intensity_processed/1min/1min_accel.rds', probable reason 'No such file or directory'
Execution halted
